# Etapa 1: Build
FROM node:18-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .

# Etapa 2: Imagen Final (más ligera)
FROM node:18-alpine
WORKDIR /app
# Copiamos solo lo necesario de la etapa anterior
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app .

EXPOSE 3000
CMD ["node", "index.js"]